[package]
name = "nextgen2"
version = "0.1.0"
authors = ["Colin Rofls <colin@cmyr.net>"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
crossbeam = "0.4"
mio = "0.6"
libc = "*"
unix-named-pipe = "0.2.0"
rand = "*"

